### ISSUE TITLE
[support] Why is this preferable over native HTML input?

### ISSUE THREAD

**Issue by lolmaus** [dockyard/ember-one-way-input#1]
Hey Dockyard!

Stumbled upon your addon in Ember Weekly.

As I understand, the same result can be achieved without any extra addon/component, with native HTML form elements:

```hbs
{{one-way-input
  value=currentValue
  update=(action (mut currentValue))
}}

<input
  value={{currentValue}}
  oninput={{action (mut currentValue) value="target.value"}}
>
```

What's the benefit?

**Comment by danmcclain** [comment]
If you edit a text input, the cursor will always go to the end of the input because of the bindings. I can make a jsbin in a bit to show you the issue

**Comment by lolmaus** [comment]
Please do!

I've also noticed that your source code exposes some hooks.

It would be awesome if you documented both the native issue and the hooks!

**Comment by poteto** [comment]
I'll update the readme! Thanks :)

**Comment by danmcclain** [comment]
http://jsbin.com/jeheku/1/edit?html,css,js,output

You can't use `mut` with the native input event, as it returns an object

**Comment by lolmaus** [comment]
@danmcclain, wut?

![herpderp](https://emoji.slack-edge.com/T0451CN7C/herpderp/3ef88d6d12f2e03a.png)

https://ember-twiddle.com/7dc033ebfc86f779e100

**Comment by danmcclain** [comment]
Twiddle link isnt working, but broken with mut in this example: http://jsbin.com/qidenisuka/edit?html,css,js,output

**Comment by lolmaus** [comment]
@danmcclain Because you dropped `value="target.value"` that exists in the top post.

**Comment by danmcclain** [comment]
@lolmaus Ah, thanks, I missed that. Still shows the janky cursor! http://jsbin.com/juxedi/edit?html,css,js,output

**Comment by lolmaus** [comment]
Thank you @poteto. But the hook(s) still not documented!
