### ISSUE TITLE
Infinite loop for input values that do not require sanitization

### ISSUE THREAD

**Issue by michaeldupuisjr** [dockyard/ember-one-way-input#11]
There appears to be an issue in which inputs whose values do not require sanitization invoke the action being passed into one-way-input. This causes an infinite loop, as the value for the input is always changing as the action fires in each loop.

For example, inside of `_processNewValue()`, the default value of `_sanitizedValue` is `undefined` while `sanitizeInput` returns `false`:

```js
  _processNewValue(rawValue) {
    const value = this.sanitizeInput(rawValue);

    if (this._sanitizedValue !== value) {
      this._sanitizedValue = value;
      this.attrs.update(value);
    }
  }
```

**Comment by tschoartschi** [comment]
Seems I've encoutered a similar issue. I can not debug it right now, but the stacktrace looks as follows (maybe this helps to see where the problem arises):

![problem-ember-one-way](https://cloud.githubusercontent.com/assets/1695329/11588499/6f9322fa-9a81-11e5-8c51-f29d6131aa83.jpg)
