### ISSUE TITLE
Ember twiddle link in readme broken

### ISSUE THREAD

**Issue by drspaniel** [dockyard/ember-one-way-input#9]
it just opens a new empty twiddle

**Comment by kellyselden** [comment]
Works for me.

**Comment by drspaniel** [comment]
Works for me in chrome, doesn't work in safari

**Comment by rwjblue** [comment]
twiddle has a bug in safari

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-twiddle/issues/274
